module.exports = [
	{
		default:true,
		title:'Free',
		id:'free',
		features: [
			'YouTube hosting only',
			'Videopath branding',
			'-',
			'-',
			'-',
			'-',
			'!Hosting options',
			'YouTube',
			'-',
			'-',
			'-',
			'-',
			'-',
			'!Branded player',
			'Videopath branding',
			'-',
			'-',
			'!Player settings',
			'Basic Settings',
			'-',
			'-',
			'-',
			'-',
			'-',
			'!Analytics',
			'Simple dashboard',
			'-',
			'-',
			'!Support',
			'Email support',
			'-',
			'-'
		],
		subscribable: true
	},
	{
		title:'Pro',
		id:'pro-plus',
		features: [
			'Professional hosting options',
			'Customizable player branding',
			'Additional player settings',
			'Google Analytics integration',
			'-',
			'-',
			'!Hosting options',
			'YouTube',
			'Vimeo',
			'Wistia',
			'-',
			'-',
			'-',
			'!Branded player',
			'Custom logo',
			'Company colors',
			'-',
			'!Player settings',
			'End screen customization',
			'Continuous playback',
			'Video resizing',
			'-',
			'-',
			'-',
			'!Analytics',
			'Advanced dashboard',
			'Google analytics',
			'-',
			'!Support',
			'Email support',
			'Phone support',
			'-'

		],
		subscribable: true
	},
	{
		id:'enterprise',
		title:'Enterprise',
		features: [
			'Enterprise hosting options',
			'White-label player',
			'Advanced player settings',
			'3rd party analytics integration',
			'Dedicated account manager',
			'Multiple client accounts',
			'!Hosting options',
			'YouTube',
			'Vimeo',
			'Wistia',
			'Brightcove',
			'3rd party',
			'Videopath',
			'!Branded player',
			'Custom logo',
			'Company colors',
			'Company font',
			'!Player settings',
			'End screen customization',
			'Continuous playback',
			'Video resizing',
			'Password protection',
			'Offline player',
			'Extended mobile support',
			'!Analytics',
			'Advanced dashboard',
			'Google analytics',
			'3rd party integration',
			'!Support',
			'Dedicated account manager',
			'Video consulting',
			'Dedicated technical support'
		],
		subscribable: false	
	}
];
